
name: CI

on:
  push:
    branches:
      - main
      - calculator

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.5.1'  # Adjust the Node.js version to 20.5.1

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test